//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublicChatBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bot
    {
        public Bot()
        {
            this.Bridge_BotUser = new HashSet<Bridge_BotUser>();
            this.contents = new HashSet<content>();
        }
    
        public string userName { get; set; }
        public string description { get; set; }
        public string token { get; set; }
        public byte sendCountDay { get; set; }
        public int lastUpdateId { get; set; }
        public int shanseErsaleMohtavayeTekrari { get; set; }
    
        public virtual ICollection<Bridge_BotUser> Bridge_BotUser { get; set; }
        public virtual ICollection<content> contents { get; set; }
    }
}
