//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublicChatBot
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BotsEntities : DbContext
    {
        public BotsEntities()
            : base("name=BotsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bot> Bots { get; set; }
        public virtual DbSet<Bridge_BotUser> Bridge_BotUser { get; set; }
        public virtual DbSet<content> contents { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
