//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublicChatBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Bridge_BotUser = new HashSet<Bridge_BotUser>();
            this.contents = new HashSet<content>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string lastName { get; set; }
        public Nullable<byte> type { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual ICollection<Bridge_BotUser> Bridge_BotUser { get; set; }
        public virtual ICollection<content> contents { get; set; }
    }
}
