//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Channel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Channel
    {
        public Channel()
        {
            this.User_Channel = new HashSet<User_Channel>();
        }
    
        public int Id { get; set; }
        public string Link { get; set; }
        public Nullable<int> Member { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> GroupId { get; set; }
        public byte StateAdd { get; set; }
        public byte ShowOrder { get; set; }
        public Nullable<int> ChatIdAdder { get; set; }
        public Nullable<System.DateTime> DateTimeAdd { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual ICollection<User_Channel> User_Channel { get; set; }
    }
}
