//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Channel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.User_Channel = new HashSet<User_Channel>();
        }
    
        public int ChatId { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<User_Channel> User_Channel { get; set; }
    }
}
